<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="64115" started-at="2018-04-30T11:13:00Z" finished-at="2018-04-30T11:14:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64115" started-at="2018-04-30T11:13:00Z" finished-at="2018-04-30T11:14:04Z">
      <class name="com.puma.test.Verify_Product_added_to_cart">
        <test-method status="PASS" signature="openapplication()[pri:0, instance:com.puma.test.Verify_Product_added_to_cart@1593948d]" name="openapplication" is-config="true" duration-ms="53931" started-at="2018-04-30T16:43:00Z" finished-at="2018-04-30T16:43:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapplication -->
        <test-method status="FAIL" signature="verifyproduct()[pri:0, instance:com.puma.test.Verify_Product_added_to_cart@1593948d]" name="verifyproduct" duration-ms="10054" started-at="2018-04-30T16:43:54Z" finished-at="2018-04-30T16:44:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy9.click(Unknown Source)
	at com.puma.page.LoginPage.menclick(LoginPage.java:41)
	at com.puma.test.Verify_Product_added_to_cart.verifyproduct(Verify_Product_added_to_cart.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyproduct -->
        <test-method status="PASS" signature="closeapp()[pri:0, instance:com.puma.test.Verify_Product_added_to_cart@1593948d]" name="closeapp" is-config="true" duration-ms="103" started-at="2018-04-30T16:44:04Z" finished-at="2018-04-30T16:44:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
      </class> <!-- com.puma.test.Verify_Product_added_to_cart -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
